name: Node.js CI

on:
  push:
    branches: ["prod"]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [20.11.0]

    steps:
    - uses: actions/checkout@v3

    # Add this step to create .env file
    - name: Create .env file
      run: |
        echo "DATABASE_URL=${{secrets.DATABASE_URL}}" >> .env
        echo "SECRET_KEY=${{secrets.SECRET_KEY}}" >> .env
        echo "NEXT_PUBLIC_BASE_URL=${{secrets.NEXT_PUBLIC_BASE_URL}}" >> .env
        echo "NEXT_PUBLIC_SUPABASE_KEY=${{secrets.NEXT_PUBLIC_SUPABASE_KEY}}" >> .env
        echo "NEXT_PUBLIC_SUPABASE_PROJECT_URL=${{secrets.NEXT_PUBLIC_SUPABASE_PROJECT_URL}}" >> .env
        echo "RESEND_API_KEY=${{secrets.RESEND_API_KEY}}" >> .env

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
        
    - run: yarn
    - run: yarn build
    - run: cd /home/escolaprime/actions-runner/_work/Escola-Prime/Escola-Prime
    - run: pm2 restart 0
